### ISSUE TITLE
Update manifest file template for a LoadBalancedWebApp

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli-v2#198]
## Story
As a ECS CLI v2 user that's not familiar with AWS services,  
I want the generated manifest for an application to not have any service-specific terminology,  
So that I can easily configure my application's infrastructure without ramping up on additional concepts.

## Acceptance Criteria
The manifest file for a Load Balanced Web App generated should be:
```yaml
# For all the available properties, please visit:
# <link to our documentation>/manifests/load-balanced-web-app.md
version: '0.1'
name: {appName}
type: load-balanced-web-app
image:
  build: {dockerFilePath}

# Requests to this path will be forwarded to your application.
http:
  path: '*'
```
I'm aiming to be terse and have a very low barrier of entry.  
The full spec for reference is:
```yaml
version: string 
name: string            # App name
type: load-balanced-web-app

image:
  build: string         # Path to your Dockerfile. Required.
  tag: string           # Changes the tag of the image. Default image name is the app's name. Default tag is "latest".
  port: integer         # Container's port. By default 8080.

cpu: integer            # Number of CPU units for the task. Defaults to 512.
memory: integer         # Amount in MiB used by the task. Defaults to 512.
count: integer          # Number of tasks that should be running in the service. Defaults to 1.

http:                # Add a target group to the environment's load balancer.              
  path: string           # Requests to this path will be forwarded to your service. Required.
  method: string         # Method to restrict requests to the service. Defaults to "*".

public: boolean        # Assign public IP address. Defaults to false.

observability: boolean # Enable AppMesh. Defaults to true.

scaling:               # Optional configuration for scaling your service.
  minCount: integer      # Required. Minimum number of tasks that should be running.
  maxCount: integer      # Required. Maximum number of tasks that should be running.
  
  # At least one of these scaling targets must be provided:
  targetCpu: integer           # Scale based on the average cpu utilization of the tasks in your service.
  targetMemory: integer        # Scale based on the average memory utilization.
  targetRequests: integer      # Scale based on the number of requests completed.
  
  cooldown: # Optional amount of time before another scaling activity starts
    scaleIn: integer     # Block other scale in events for X seconds. Defaults to 60.
    scaleOut: integer    # Block other sclae out events for X seconds. Defaults to 60. 

variables:               # Optional container environment variables for plain strings 
  <name>: <value>        # Values are plain strings
  
secrets:                 # Optional container environment variables for secure strings in SSM.
  <name>:
    from: <value>        # Parameter name in SSM.

environments:                    # Override fields for an Archer environment.
  <name>:
    <fields...>
```
