### ISSUE TITLE
'null' values are not allowed in templates

### ISSUE THREAD

**Issue by montanaflynn** [aws/amazon-ecs-cli-v2#963]
I ran `ecs-preview init` and after entering the values for a `Backend App` I got this error:

```
Error!
Error: deploy application: check if changeset is empty: create change set ecscli-74a966b0-04f2-4121-84a9-1d3fcbea4f8d for stack test-api-test-test-api: ValidationError: [/Resources/TaskDefinition/Type/ContainerDefinitions/0/Secrets] 'null' values are not allowed in templates
	status code: 400, request id: 4802215e-39eb-4c9a-9d66-60c87c8b2f37: describe change set ecscli-74a966b0-04f2-4121-84a9-1d3fcbea4f8d for stack test-api-test-test-api: ValidationError: Stack [test-api-test-test-api] does not exist
	status code: 400, request id: ac9768f9-a088-48e6-8804-be667e9765df
```

Full logs:

```
$ ecs-preview init
Note: It's best to run this command in the root of your Git repository.
Welcome to the ECS CLI! We're going to walk you through some questions
to help you get set up with a project on ECS. A project is a collection of
containerized applications (or micro-services) that operate together.

Looks like you have some projects already.

? Would you like to use one of your existing projects? No
Ok, let's create a new project then.

? What would you like to name your project? example-api

? Which type of infrastructure pattern best represents your application? Backend App

? What do you want to name this Backend App? example-api

? Which Dockerfile would you like to use for example-api? ./Dockerfile

Parsing dockerfile at path ./Dockerfile for application example-api...
✔ It looks like your Dockerfile exposes port 8080. We'll use that to route traffic to your container from your load balancer.
Ok great, we'll set up a Backend App named example-api in project example-api listening on port 8080.
✔ Created the infrastructure to manage container repositories under project example-api.

✔ Wrote the manifest for example-api app at ecs-project/example-api/manifest.yml
Your manifest contains configurations like your container size and ports.

✔ Created ECR repositories for application example-api.
All right, you're all set for local development.

? Would you like to deploy a test environment? Yes
✔ Created the infrastructure for the test environment.
- Virtual private cloud on 2 availability zones to hold your services     [Complete]
  - Internet gateway to connect the network to the internet               [Complete]
  - Public subnets for internet facing services                           [Complete]
  - Private subnets for services that can't be reached from the internet  [Complete]
  - Routing tables for services to talk with each other                   [Complete]
- ECS Cluster to hold your services                                       [Complete]
- Application load balancer to distribute traffic                         [Complete]
✔ Linked account ... and region us-east-1 project example-api.
✔ Created environment test in region us-east-1 under project example-api.
Sending build context to Docker daemon  229.9kB
Step 1/15 : ...
Step 14/15 : EXPOSE 8080
 ---> Running in ...
Successfully built ...
Successfully tagged ....dkr.ecr.us-east-1.amazonaws.com/example-api/example-api:...
Login Succeeded
The push refers to repository [....dkr.ecr.us-east-1.amazonaws.com/example-api/example-api]
...: Pushed
...: digest: sha256:... size: ....

Error!
Error: deploy application: check if changeset is empty: create change set ecscli-74a966b0-04f2-4121-84a9-1d3fcbea4f8d for stack test-api-test-test-api: ValidationError: [/Resources/TaskDefinition/Type/ContainerDefinitions/0/Secrets] 'null' values are not allowed in templates
	status code: 400, request id: 4802215e-39eb-4c9a-9d66-60c87c8b2f37: describe change set ecscli-74a966b0-04f2-4121-84a9-1d3fcbea4f8d for stack test-api-test-test-api: ValidationError: Stack [test-api-test-test-api] does not exist
	status code: 400, request id: ac9768f9-a088-48e6-8804-be667e9765df
```
```

**Comment by kohidave** [comment]
I'm so sorry @montanaflynn ! Yea, that's a super confusing message. 

Could you paste your manifest.yml (in `project/example-api/manifest.yml`) [or send it to me at killmond@amazon.com if it has sensitive info)? 

My hunch is that there's a secret value there which doesn't have an actual value in SSM and that's why you're seeing this issue. I'll try to reproduce it on my end, too, to confirm.

**Comment by montanaflynn** [comment]
It originally happened on a default backend app, so I guess the manifest was:

```
# The manifest for the "typeset-api" application.
# Read the full specification for the "Backend App" type at:
#  https://github.com/aws/amazon-ecs-cli-v2/wiki/Manifests#backend-app

# Your application name will be used in naming your resources like log groups, services, etc.
name: example-api

# Your application is reachable at "http://typeset-api.${ECS_APP_DISCOVERY_ENDPOINT}:8080" but is not public.
type: Backend App

image:
  # Path to your application's Dockerfile.
  build: ./Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 8080

# Number of CPU units for the task.
cpu: 256
# Amount of memory in MiB used by the task.
memory: 512
# Number of tasks that should be running in your service.
count: 1

# Optional fields for more advanced use-cases.
#
#variables:                    # Pass environment variables as key value pairs.
#  LOG_LEVEL: info

#secrets:                      # Pass secrets from AWS Systems Manager (SSM) Parameter Store.
#  GITHUB_TOKEN: GITHUB_TOKEN  # The key is the name of the environment variable, the value is the name of the SSM      parameter.

# You can override any of the values defined above by environment.
#environments:
#  test:
#    count: 2               # Number of tasks to run for the "test" environment.
```

I can reproduce it on a different project by including environments so this works:

```
name: example-app

type: Load Balanced Web App

image:
  build: ./Dockerfile
  port: 8080

http:
  path: '/'

cpu: 512
memory: 1024

count: 3

variables:                    
  ENVIRONMENT: production

# environments:
#   staging:
#     count: 1
#     variables:
#       ENVIRONMENT: staging
```

But this causes the error:

```
name: example-app

type: Load Balanced Web App

image:
  build: ./Dockerfile
  port: 8080

http:
  path: '/'

cpu: 512
memory: 1024

count: 3

variables:                    
  ENVIRONMENT: production

environments:
  staging:
    count: 1
    variables:
      ENVIRONMENT: staging
```

I'm using `ecs-preview version: v0.0.9` on a mac.
